### ISSUE TITLE
The setup field in services.yml is confusing and potentially wrong

### ISSUE THREAD

**Issue by stefansavev-o** [Originate/exocom#154] opened 2017-07-06 11:35 UTC
exo setup runs the setup command from each services.yml locally. However, here are a couple of scenarios where this is not desirable.

1. glide install, but my system is not pre-installed with go. I don't need to install go to run the docker containers

2. yarn install on a Mac. It install node dependencies locally with binary code for Mac. The docker file picks those dependencies and the container fails when started.

**Comment by charlierudolph** [comment] 2017-07-06 17:06
@hugobho @kevgo can you respond to this? I'm not certain what the setup vs run command is supposed to be.

**Comment by kevgo** [comment] 2017-07-06 17:23
@stefansavev-o you are right. This is a leftover from the time before we used Docker. https://github.com/Originate/exosphere/issues/313 describes the new behavior, in which these setup steps are going to be implemented in the Dockerfile.

**Comment by kevgo** [comment] 2017-07-06 17:23
duplicate of https://github.com/Originate/exosphere/issues/313

**Closed by kevgo** 2017-07-06 17:23 UTC
